version: '2'
services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    # volumes:
    #   - ../db/postgres/data:/var/lib/postgresql/data/
    #   - ../db/postgres/tmp/:/var/run/postgresql/
    environment:
      POSTGRES_PASSWORD: macmorris
  web:
    build: 
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - UNAME=${UNAME}
    # command: bin/rails server -p 3000 --binding 0.0.0.0
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    user: ${UID}:${GID}
    working_dir: /app
    volumes:
      - .:/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
  # nginx:
  #   image: nginx:1.0
  #   # container_name: nginx-ser
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
