version: '2'
services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - /fastscratch/data/macmorris_backend:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build: 
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - UNAME=${UNAME}
    # command: bin/rails server -p 3000 --binding 0.0.0.0
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    user: ${UID}:${GID}
    working_dir: /app
    volumes:
      - .:/app
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /fastscratch/projects/macmorris_frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
