version: '2'
services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    # volumes:
    #   - ../db/postgres/data:/var/lib/postgresql/data/
    #   - ../db/postgres/tmp/:/var/run/postgresql/
    environment:
      POSTGRES_PASSWORD: macmorris
  web:
    build: .
    # command: bin/rails server -p 3000 --binding 0.0.0.0
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app  
  nginx:
    image: nginx:0.1
    # container_name: nginx-ser
    ports:
      - 80:80
    depends_on:
      - web
